spring:  profiles:    active:    - local      application:    name: SB-REACT
  
---
spring:  config:    activate:      on-profile:      - local  datasource:    initialization-mode: always    url: jdbc:h2:mem:testdb  jpa:    show-sql: true  h2:    console:      enabled: true      path: /h2debug: true

server:
  port: 8081  
---
spring:
  config:
    activate:
      on-profile:
      - dev

server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile:
      - pre

server:
  port: 8083
